CREATE TABLE USUARIO
(
ID int NOT NULL,
NOMBRE varchar(255) NOT NULL,
EMAIL varchar(255),
TELEFONO numeric(12,0) NOT NULL
);

CREATE TABLE SITIOS
(
ID int NOT NULL,
NOMBRE varchar(255) NOT NULL,
DIRECCION varchar(255),
DEPORTE varchar(255),
TELEFONO int NOT NULL,
EMAIL varchar(255),
HORARIO int NOT NULL,
PRECIO numeric(8,2),
TIEMPO_MINIMO time,
DESCRIPCION varchar(1024),
IMAGEN varchar(255)
 
);

CREATE TABLE RESERVAS
(
ID int NOT NULL ,
USUARIO int NOT NULL  ,
SITIO int NOT NULL  ,
HORA time,
DURACION time,
PRECIO numeric(8,2)
);

CREATE TABLE OPCIONES
(
ID int NOT NULL,
RECORDATORIO boolean NOT NULL,
PAGO boolean NOT NULL

);
